from os import getenv

ALL_SPRINTS_BY_BOARD_URL = getenv('ALL_SPRINTS_BY_BOARD_URL')
ALL_ISSUES_BY_SPRINTS_ID_URL = getenv('ALL_ISSUES_BY_SPRINTS_ID_URL')
USERNAME = getenv('USERNAME')
PASSWORD = getenv('PASSWORD')
